# Generated by Django 3.1 on 2022-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20220603_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
