# Generated by Django 3.1 on 2022-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20220604_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(null=True),
        ),
    ]
