# Generated by Django 3.1 on 2022-11-03 17:32

import MainApp.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20221023_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=MainApp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='images'),
        ),
    ]
